"""Generate package scaffolding: __init__.py and pyproject.toml."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..parser import SchemaInfo


def generate_init(
    schema: SchemaInfo,
    package_name: str,
    client_class_name: str,
    schema_class_name: str,
    mutation_class_name: str = "",
    regen_command: str = "",
) -> str:
    """Return the contents of ``__init__.py`` for the generated package."""
    if regen_command:
        docstring = (
            f'"""GraphQL client package generated by `graphql_client_generator`: {package_name}.\n'
            f"\n"
            f"To regenerate:\n"
            f"    {regen_command}\n"
            f'"""'
        )
    else:
        docstring = (
            f'"""GraphQL client package generated by `graphql_client_generator`: {package_name}."""'
        )

    schema_imports = schema_class_name
    if mutation_class_name:
        schema_imports += f", {mutation_class_name}"

    all_entries = [
        f"{client_class_name!r}",
        f"{schema_class_name!r}",
    ]
    if mutation_class_name:
        all_entries.append(f"{mutation_class_name!r}")
    all_entries.extend(["'Variable'", "'enums'", "'inputs'", "'outputs'", "'schema'"])

    lines = [
        docstring,
        "",
        f"from .client import {client_class_name}",
        f"from .schema import {schema_imports}",
        "from . import enums",
        "from . import inputs",
        "from . import outputs",
        "from . import schema",
        "from ._runtime.builder import Variable",
        "",
        f"__all__ = [{', '.join(all_entries)}]",
        "",
    ]
    return "\n".join(lines)


def generate_pyproject(package_name: str) -> str:
    """Return the contents of ``pyproject.toml`` for the generated package."""
    return f"""\
[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{package_name}"
version = "0.1.0"
description = "Generated GraphQL client for {package_name}"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "graphql-core>=3.2",
]
"""
